Repository sad-course/SEIF, pull requests merged in 2025-02, with the labels that each got.

#66 chore: Define pylint_django and set load plugin in pre-commit config
  .pre-commit-config.yaml
  requirements.txt
Labels: bug

#67 Feature/postgres configuration
  .gitignore
  .pre-commit-config.yaml
  CONTRIBUTING.md
  README.md
  SEIF/settings.py
  pyproject.toml
  requirements.txt
  utils/__init__.py
  utils/admin.py
  utils/apps.py
  utils/management/commands/__init__.py
  utils/management/commands/checkdb.py
  utils/management/commands/env.py
  utils/management/commands/makenv.py
  utils/migrations/__init__.py
  utils/models.py
  utils/tests.py
  utils/views.py
Labels: documentation, enhancement

#77 Feature - Autenticação via credenciais
  SEIF/settings.py
  SEIF/urls.py
  accounts/backends.py
  accounts/forms.py
  accounts/static/js/profile_script.js
  accounts/templates/accounts/profile.html
  accounts/templates/accounts/signup.html
  accounts/urls.py
  accounts/views.py
  core/templates/core/base.html
  media/accounts/users/avatar/IFRN2.png
  media/accounts/users/avatar/Progress.png
  media/accounts/users/avatar/Progress_RsNsaVD.png
  media/accounts/users/avatar/Rectangle_37.png
Labels: enhancement

#88 Listagem de eventos, filtragem, paginação e pesquisa na tela Home
  SEIF/settings.py
  core/filters.py
  core/static/img/mainbanner.png
  core/templates/core/event_detail.html
  core/templates/core/index.html
  core/urls.py
  core/views.py
  management/admin.py
  requirements.txt
Labels: enhancement

#85 Criar listagem de participantes no management
  management/templates/management/participants.html
  management/urls.py
  management/views.py
Labels: enhancement

#95 criar listagem home, paginação de tabelas e listagem organizadores
  accounts/admin.py
  core/templates/core/base.html
  core/templates/core/index.html
  core/views.py
  management/admin.py
  management/migrations/0013_alter_certificate_activity.py
  management/templates/management/analytics_home.html
  management/templates/management/base.html
  management/templates/management/event_submit_dashboard.html
  management/templates/management/index.html
  management/templates/management/organizers.html
  management/templates/management/participants.html
  management/urls.py
  management/views.py
Labels: enhancement

#99 Feature/event request
  .pre-commit-config.yaml
  SEIF/ckeditor_config.py
  accounts/management/commands/populate_user_groups.py
  core/templates/core/base.html
  core/templates/core/event_detail.html
  core/templates/core/index.html
  management/admin.py
  management/forms.py
  management/management/commands/copy_banner_default_to_media.py
  management/management/commands/populate_activity_types.py
  management/models.py
  management/static/django_ckeditor_5/ckeditor_custom.css
  management/static/img/event-banner-default.jpg
  management/static/js/event_form.js
  management/static/svg/calendar-management.svg
  management/templates/management/base.html
  management/templates/management/edit_event.html
  management/templates/management/index.html
  management/templates/management/participants.html
  management/templates/management/request_create_event.html
  management/urls.py
  management/views.py
  pyproject.toml
  requirements.txt
  utils/management/commands/seed_db.py
Labels: bug, enhancement
