Repository sad-course/SEIF, pull requests merged in 2025-01, with the labels that each got.

#37 Tela da Home e detalhes de um evento
  core/static/js/script.js
  core/static/svg/hamburguer-menu.svg
  core/static/svg/keyboard_arrow_down.svg
  core/templates/core/base.html
  core/templates/core/event_detail.html
  core/templates/core/index.html
  core/urls.py
  core/views.py
  theme/static_src/src/styles.css
  theme/static_src/tailwind.config.js
Labels: enhancement

#43 Configure precommit tools (black formatter & pylint)
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/task.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/black.yml
  .gitignore
  .pre-commit-config.yaml
  README.md
  SEIF/asgi.py
  SEIF/settings.py
  SEIF/urls.py
  SEIF/wsgi.py
  accounts/apps.py
  core/apps.py
  core/templates/core/base.html
  core/templates/core/event_detail.html
  core/templates/core/index.html
  core/urls.py
  core/views.py
  manage.py
  management/apps.py
  management/static/js/management_script.js
  management/templates/management/base.html
  management/templates/management/index.html
  management/urls.py
  management/views.py
  pyproject.toml
  requirements.txt
  theme/apps.py
  theme/static_src/src/styles.css
  theme/static_src/tailwind.config.js
Labels: documentation, enhancement

#42 Feature/front screens d
  SEIF/urls.py
  accounts/templates/accounts/my_certificates.html
  accounts/templates/accounts/my_events.html
  accounts/urls.py
  accounts/views.py
  core/static/svg/download-icon.svg
  core/templates/core/base.html
  core/urls.py
  core/views.py
  management/urls.py
Labels: enhancement

#39 Feature/mangement listing
  management/static/js/management_script.js
  management/static/svg/activities.svg
  management/static/svg/calendar-management.svg
  management/static/svg/hamburguer-menu.svg
  management/static/svg/icon-calendar.svg
  management/static/svg/organizer.svg
  management/static/svg/participants.svg
  management/templates/management/base.html
  management/templates/management/index.html
  management/templates/management/organizers.html
  management/templates/management/participants.html
  management/urls.py
  management/views.py
  theme/static_src/src/styles.css
  theme/static_src/tailwind.config.js
Labels: enhancement

#51 Feature/create event
  .pre-commit-config.yaml
  accounts/templates/accounts/my_events.html
  management/static/js/management_script.js
  management/templates/management/base.html
  management/templates/management/create_event.html
  management/templates/management/request_create_event.html
  management/urls.py
  management/views.py
Labels: enhancement

#58 fix: Remove breakline in AUTH config
  SEIF/settings.py
Labels: bug
